languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
# ... CONFIG CONTENT ...
exclude_paths:
- "Gemfile.lock"
- "react/webpack.config.js"
- "react/karma.conf.js"
- "react/test"
- "app/assets/stylesheets"
- "app/assets/javascripts/cable.js"
- "db/schema.rb"
- "spec"
- "assets/javascripts/bundle.js"
- "app/assets/javascripts/application.js"
